/*
    Framework for building object relational database apps
    Copyright (C) 2025  Featherbone LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/**
    Material icon name -> IconPark icon name.

    Featherbone's icons used to be Material font glyphs and are now
    IconPark SVGs (media/icons/iconpark). Workbooks, forms and packages
    saved before the switch still carry Material names; `f.icon()`
    translates them through this table so they keep working, and shows
    the old font glyph for a name that is in neither list.
    @module IconMap
*/
const legacyIcons = {
    "account_balance": "bank",
    "account_tree": "tree-diagram",
    "add": "plus",
    "add_circle": "add-one",
    "add_circle_outline": "add-one",
    "add_task": "list-add",
    "admin_panel_settings": "setting-config",
    "architecture": "triangle-ruler",
    "archive": "file-zip",
    "arrow_back": "arrow-left",
    "arrow_downward": "arrow-down",
    "arrow_drop_down": "down",
    "arrow_drop_up": "up",
    "arrow_forward": "arrow-right",
    "arrow_upward": "arrow-up",
    "article": "file-text",
    "assignment": "checklist",
    "attach_money": "dollar",
    "auto_graph": "trend",
    "autorenew": "refresh",
    "backup_table": "table-file",
    "bar_chart": "chart-histogram",
    "block": "forbid",
    "bookmark": "bookmark",
    "bug_report": "bug",
    "build": "tool",
    "business": "building-one",
    "calculate": "calculator-one",
    "calendar_month": "calendar",
    "calendar_today": "calendar",
    "call_received": "arrow-left-down",
    "cancel": "close-one",
    "check": "check",
    "check_circle": "check-one",
    "check_circle_outline": "check-one",
    "checklist_rtl": "list-checkbox",
    "chevron_left": "left",
    "chevron_right": "right",
    "clear": "close",
    "close": "close",
    "cloud_done": "check-one",
    "cloud_download": "download-one",
    "cloud_off": "close-wifi",
    "cloud_upload": "upload-one",
    "code": "code",
    "contacts": "address-book",
    "content_copy": "copy",
    "copy": "copy",
    "copy_all": "copy",
    "currency_exchange": "exchange-four",
    "dangerous": "octagon",
    "dashboard_customize": "application-menu",
    "delete": "delete",
    "delete_outline": "delete",
    "delete_sweep": "delete-four",
    "description": "file-text",
    "domain": "building-one",
    "done": "check",
    "done_all": "check-correct",
    "donut_small": "chart-ring",
    "double_arrow": "double-right",
    "download": "download",
    "edit": "edit",
    "edit_note": "edit-two",
    "email": "mail",
    "engineering": "tool",
    "error": "close-one",
    "error_outline": "close-one",
    "event": "calendar",
    "event_available": "calendar-thirty-two",
    "event_note": "calendar-thirty",
    "expand_less": "up",
    "expand_more": "down",
    "fact_check": "checklist",
    "factory": "factory-building",
    "fast_forward": "go-ahead",
    "file_download": "download",
    "file_open": "folder-open",
    "file_upload": "upload",
    "filter_list": "filter",
    "flag": "flag",
    "folder": "folder-close",
    "folder_open": "folder-open",
    "format_list_numbered": "list-numbers",
    "format_list_numbered_rtl": "list-numbers",
    "front_hand": "palm",
    "grid_on": "cube",
    "grid_view": "chart-histogram-two",
    "group": "peoples",
    "help": "help",
    "help_outline": "help",
    "highlight_off": "close-one",
    "history": "history",
    "home": "home",
    "image": "picture",
    "import_export": "transfer-data",
    "info": "info",
    "insights": "chart-line-area",
    "inventory": "inbox",
    "inventory_2": "box",
    "key": "key",
    "keyboard_arrow_down": "down",
    "keyboard_arrow_left": "left",
    "keyboard_arrow_right": "right",
    "keyboard_arrow_up": "up",
    "keyboard_double_arrow_down": "double-down",
    "keyboard_double_arrow_up": "double-up",
    "label": "tag",
    "language": "earth",
    "layers": "layers",
    "library_add": "copy-one",
    "link": "link",
    "list": "list",
    "local_shipping": "truck",
    "lock": "lock",
    "lock_clock": "lock",
    "lock_open": "unlock",
    "login": "login",
    "logout": "logout",
    "mail": "mail",
    "manage_accounts": "config",
    "map": "map-draw",
    "menu": "hamburger-button",
    "more_horiz": "more",
    "more_vert": "more-two",
    "next_plan": "next",
    "note_add": "file-addition",
    "notifications": "remind",
    "open_in_new": "efferent-four",
    "package_2": "box",
    "pause": "pause",
    "pause_circle": "pause-one",
    "payments": "bank-card",
    "pending": "more-two",
    "people": "peoples",
    "person": "user",
    "phone": "phone-telephone",
    "photo": "picture",
    "picture_as_pdf": "file-pdf",
    "pie_chart": "chart-pie",
    "place": "local-pin",
    "play_arrow": "play",
    "play_circle": "play-one",
    "playlist_remove": "list-fail",
    "post_add": "file-addition-one",
    "precision_manufacturing": "robot-two",
    "price_check": "tag-one",
    "print": "printer",
    "public": "earth",
    "published_with_changes": "refresh-one",
    "queue": "add-text",
    "radio_button_unchecked": "round",
    "recent_actors": "address-book",
    "redo": "redo",
    "refresh": "refresh",
    "remove": "minus",
    "remove_circle_outline": "reduce-one",
    "report_error": "close-one",
    "report_problem": "caution",
    "route": "nested-arrows",
    "rule": "list-fail",
    "save": "save",
    "schedule": "time",
    "search": "search",
    "security": "protect",
    "send": "send",
    "settings": "setting-two",
    "share": "share-one",
    "shopping_cart": "shopping-cart-one",
    "shopping_cart_checkout": "shopping-cart-add",
    "sort_by_alpha": "alphabetical-sorting",
    "speed": "speed-one",
    "square": "square",
    "star": "star",
    "start": "play-one",
    "stop": "square",
    "stop_circle": "square",
    "storage": "data-server",
    "store": "shop",
    "summarize": "report",
    "supervised_user_circle": "peoples-two",
    "sync": "refresh-one",
    "sync_alt": "adjustment",
    "table_chart": "table",
    "table_rows": "table",
    "target": "target",
    "thumb_up": "thumbs-up",
    "timeline": "timeline",
    "today": "calendar-dot",
    "trending_up": "chart-line",
    "tune": "adjustment",
    "undo": "undo",
    "upgrade": "up-one",
    "upload": "upload",
    "view_kanban": "layout-five",
    "view_timeline": "timeline",
    "visibility": "preview-open",
    "visibility_off": "preview-close-one",
    "vpn_key": "key",
    "warning": "caution",
    "waving_hand": "hand-up",
    "work": "briefcase",
    "zoom_in": "zoom-in",
    "zoom_out": "zoom-out"
};

export default Object.freeze(legacyIcons);
