/*
    Tiny Mithril "server side" renderer for unit tests.

    render(component, attrs) runs the component lifecycle hooks that
    matter for building a tree (oninit, then view) and recursively
    expands nested components, returning the raw vnode tree. No DOM is
    created; oncreate/onupdate hooks are not called.

    toJSON(tree) turns the vnode tree into plain data for assertions and
    golden files: {tag, attrs, children}, with function-valued attrs
    replaced by "<fn>", mithril internals dropped, and ids generated by
    f.createId (see browser-env stableIds) replaced with "<id>".

    find(tree, predicate) / findAll / text(tree) help with structural
    assertions (buttons present, labels, disabled flags).
*/
/*jslint node*/
"use strict";

const STABLE_ID = /fbid\d+/g;

function instantiate(component, vnode) {
    let state;
    if (typeof component === "function") {
        // Closure or class component
        state = (
            component.prototype && component.prototype.view
            ? new component(vnode)
            : component(vnode)
        );
    } else {
        state = Object.create(component);
    }
    vnode.state = state;
    if (typeof state.oninit === "function") {
        state.oninit.call(state, vnode);
    }
    return state;
}

function expand(node, depth) {
    if (depth > 60) {
        throw new Error("render: component nesting too deep");
    }
    if (Array.isArray(node)) {
        return node.map((n) => expand(n, depth));
    }
    if (!node || typeof node !== "object") {
        return node;
    }
    if (node.tag && typeof node.tag !== "string") {
        let vnode = {
            tag: node.tag,
            attrs: node.attrs || {},
            children: node.children,
            key: node.key
        };
        let state = instantiate(node.tag, vnode);
        let out = state.view.call(state, vnode);
        return {
            component: true,
            name: (
                node.tag.__name ||
                (node.attrs && node.attrs.__name) ||
                undefined
            ),
            children: [expand(out, depth + 1)]
        };
    }
    if (node.children !== undefined && node.children !== null) {
        node.children = expand(node.children, depth + 1);
    }
    return node;
}

/**
    Render a component (object with view, optional oninit) with attrs.
    Returns {state, vnode, tree}.
*/
function render(component, attrs) {
    let vnode = {tag: component, attrs: attrs || {}};
    let state = instantiate(component, vnode);
    let tree = expand(state.view.call(state, vnode), 0);
    return {state, vnode, tree};
}

function cleanString(s) {
    return s.replace(STABLE_ID, "<id>");
}

function toJSON(node) {
    if (Array.isArray(node)) {
        return node.map(toJSON).filter((n) => n !== undefined);
    }
    if (node === null || node === undefined || typeof node === "boolean") {
        return undefined;
    }
    if (typeof node === "string") {
        return cleanString(node);
    }
    if (typeof node === "number") {
        return node;
    }
    if (node.component) {
        return {component: true, children: toJSON(node.children)};
    }
    if (node.tag === "#") {
        return cleanString(String(node.children));
    }
    if (node.tag === "[") {
        return {fragment: toJSON(node.children || [])};
    }
    let out = {tag: node.tag};
    let attrs = {};
    let src = Object.assign({}, node.attrs);
    // Mithril moves `class` to `className`; report it as class
    if (src.className !== undefined) {
        src.class = src.className;
        delete src.className;
    }
    Object.keys(src).sort().forEach(function (k) {
        let v = src[k];
        if (v === undefined || v === null || k === "key") {
            return;
        }
        if (typeof v === "function") {
            attrs[k] = "<fn>";
        } else if (typeof v === "string") {
            attrs[k] = cleanString(v);
        } else if (v && typeof v === "object") {
            attrs[k] = JSON.parse(cleanString(JSON.stringify(v)));
        } else {
            attrs[k] = v;
        }
    });
    if (Object.keys(attrs).length) {
        out.attrs = attrs;
    }
    if (node.text !== undefined && node.text !== null) {
        out.children = [cleanString(String(node.text))];
    } else if (node.children !== undefined && node.children !== null) {
        let c = toJSON(Array.isArray(node.children)
            ? node.children
            : [node.children]);
        if (c.length) {
            out.children = c;
        }
    }
    return out;
}

// The toolbar renders an invisible copy of every button only to measure
// widths (toolbar.js measureNode). Those copies are not what a user sees
// or clicks, so searches skip them; golden snapshots (toJSON) keep them.
function isMeasureOnly(node) {
    let c = node.attrs && (node.attrs.className || node.attrs.class);
    return (
        typeof c === "string" &&
        c.split(/\s+/).includes("fb-toolbar-measure")
    );
}

function walk(node, fn) {
    if (Array.isArray(node)) {
        node.forEach((n) => walk(n, fn));
        return;
    }
    if (!node || typeof node !== "object" || isMeasureOnly(node)) {
        return;
    }
    fn(node);
    if (node.children !== undefined && node.children !== null) {
        walk(node.children, fn);
    }
}

function findAll(tree, pred) {
    let out = [];
    walk(tree, function (n) {
        if (typeof n.tag === "string" && pred(n)) {
            out.push(n);
        }
    });
    return out;
}

function find(tree, pred) {
    return findAll(tree, pred)[0];
}

function text(tree) {
    let parts = [];
    walk(tree, function (n) {
        if (n.tag === "#") {
            parts.push(String(n.children));
        } else if (typeof n.tag === "string" && n.text !== undefined &&
                n.text !== null) {
            parts.push(String(n.text));
        }
    });
    return parts.join(" ").replace(/\s+/g, " ").trim();
}

// Selectors
const byTag = (tag) => (n) => n.tag === tag;
function classOf(n) {
    let c = n.attrs && (n.attrs.className || n.attrs.class);
    return (
        typeof c === "string"
        ? c.split(/\s+/)
        : []
    );
}
const byClass = (cls) => (n) => classOf(n).includes(cls);
const byId = (id) => (n) => Boolean(n.attrs && n.attrs.id === id);

module.exports = {
    render,
    toJSON,
    find,
    findAll,
    text,
    classOf,
    byTag,
    byClass,
    byId
};
